# Generated by Django 2.2.16 on 2022-01-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
            ],
        ),
    ]
